### PR TITLE
Unit tests to raise the code coverage by 18% 

### PR DESCRIPTION
**Pull request by mfarid**
Hi Kai @soarcn 

This pull request is a sample of unit test cases that we plan to contribute in order to raise the overall coverage to 80%. Code coverage is measured using Android Studio. This pull request increases code coverage of library from 0% to 18%.

| Metric | Before | After |
| --- | --- | --- |
| Coverage % | 0% | 18% |
| Lines Covered | 0 | 80 |
| Total Lines | 440 | 440 |

Please let me know if you have any questions.

Mohd Farid
DevFactory - Code Quality Team

### CODE REVIEW

**Comment by soarcn** [comment]
Hi @mfarid  Thanks for your contribution. It's fantastic.
Before I merge this PR, would you mind adding unittest to travis configuration?

**Comment by airleks** [comment]
Hi Kai

I've forked this branch from DevFactory and inserted - ./gradlew test to script section
(https://github.com/airleks/Favor/blob/staging-sample/.travis.yml)

The project build was successful (https://travis-ci.org/airleks/Favor/builds/106727478) and I see that gradle test task do not call any kind of 'androidTest' tasks here. Does this update is what you supposed us to do to deal with travis?

Best regards,
Alexey Syrtsev
DevFactory - Code Quality Team

**Comment by soarcn** [comment]
Hi @airleks 

Excellent, that's what I want.
Regarding the instrument test, ./gradlew connectedCheck  will take care of it.
Please update the PR, and I will merge it to master.

I would suggest you integrate jacoco/coveralls to make your contribution more obvious.

**Comment by airleks** [comment]
@soarcn
Done. Please check.

**Comment by soarcn** [comment]
Thanks mate!

**Pull request merged**
